import {describe, it, expect, vi} from "vitest";
import {GameEngine} from "@engine/core/GameEngine";
import {createTestWorld} from "@engine/test/createTestWorld";
import * as topology from "./NetworkTopology";
import {runConveyors} from "./ConveyorSystem";

describe("Cached connections", () => {
  it("reuses connections between ticks and invalidates edits", () => {
    const setup = new GameEngine(createTestWorld());
    setup.placeConveyor(0, 0, "right");
    setup.placeStorage(1, 0);
    const initial = setup.getWorld();
    initial.conveyors[0].carrying = Array.from({length: 3}, () => ({type: "iron", amount: 1, progress: 1}));
    initial.storages[0].capacity = 1;
    const engine = new GameEngine(initial);
    const build = vi.spyOn(topology, "buildNetworkTopology");
    engine.tick(); engine.tick();
    expect(build).toHaveBeenCalledTimes(1);
    expect(engine.getSnapshot().resources.iron).toBe(1);
    engine.placeConveyor(0, 0, "down");
    engine.placeStorage(0, 1);
    engine.tick();
    expect(build).toHaveBeenCalledTimes(2);
    expect(engine.getSnapshot().storages[1].stored.iron).toBe(1);
    engine.destroyEntityAt(0, 1);
    engine.tick();
    expect(build).toHaveBeenCalledTimes(3);
    expect(engine.getSnapshot().conveyors[0].carrying).toHaveLength(2);
    engine.placeStorage(0, 1);
    engine.tick();
    expect(build).toHaveBeenCalledTimes(4);
    expect(engine.getSnapshot().storages[1].stored.iron).toBe(1);
  });
  it("uses current per-resource machine capacity, not cached inventories", () => {
    const setup = new GameEngine(createTestWorld());
    setup.placeMachine(1, 1, "iron-smelter");
    setup.placeConveyor(1, 0, "down");
    const world = setup.getWorld();
    const network = topology.buildNetworkTopology(world);
    world.machines[0].buffer.ironPlate = 99;
    world.conveyors[0].carrying = [{type: "iron", amount: 3, progress: 1}];
    runConveyors(world, network);
    expect(world.machines[0].buffer.iron).toBe(3);
    expect(world.conveyors[0].carrying).toHaveLength(0);
    world.machines[0].buffer.iron = 99;
    world.conveyors[0].carrying = [{type: "iron", amount: 3, progress: 1}];
    runConveyors(world, network);
    expect(world.machines[0].buffer.iron).toBe(100);
    expect(world.conveyors[0].carrying[0].amount).toBe(2);
  });
});
